# Generated by Django 2.2.5 on 2019-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('Qualification', models.TextField(max_length=100)),
                ('year_of_passing', models.IntegerField()),
            ],
        ),
    ]
